// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvoHMF0Ao7g7gQLSQjwWf8Fkw6qaaZrcY',
    appId: '1:634056181582:android:e5c46cc2ba25d7c828801f',
    messagingSenderId: '634056181582',
    projectId: 'buscape-90a48',
    databaseURL: 'https://buscape-90a48-default-rtdb.firebaseio.com',
    storageBucket: 'buscape-90a48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9DgF2lTXJRJ8hPDMcXqBtb3JMEeuUUuY',
    appId: '1:634056181582:ios:2891f58c4156fd9a28801f',
    messagingSenderId: '634056181582',
    projectId: 'buscape-90a48',
    databaseURL: 'https://buscape-90a48-default-rtdb.firebaseio.com',
    storageBucket: 'buscape-90a48.appspot.com',
    iosClientId: '634056181582-irmgn52k1be7o1p7ctmreqf5u92pfkje.apps.googleusercontent.com',
    iosBundleId: 'com.example.segundoBimestre',
  );
}
